### ISSUE TITLE
Easiest way to run this app in a browser?

### ISSUE THREAD

**Issue by chinshr** [nicholasareed/reinvent#1]
@nicholasareed your help would be greatly appreciated to explain how to either run this app standalone in Chrome or to run in in cordova?

**Comment by nicholasareed** [comment]
@chinshr  Easiest way is to push to publish to GitHub Pages (you'll notice there is already a `gh-pages` branch)

Edit: you'd have a valid site such as: http://nicholasareed.github.io/reinvent/

**Comment by chinshr** [comment]
Thanks, I will try to do that. Any tips on setting up on Cordova? Just drop to www folder?

**Comment by nicholasareed** [comment]
This isn't setup for cordova. The sample app at http://famousmobileapps.com is though

**Comment by chinshr** [comment]
Thanks, this one here https://github.com/FamousMobileApps/waiting_app
